### PR TITLE
REMARKLIN, IODRYRUN and IOWETRUN included

### PR DESCRIPTION
**Pull request by anandmit93**
Included functionality for 3 RPCs - REMARKLIN, IODRYRUN, IOWETRUN

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@anandmit93: I guess you merged instead of rebasing?

**Comment by gavanderhoorn** [comment]
Actually, it might be easier for you to create a new branch (from current `HEAD`) and then only import the commits you actually want to contribute.

Something like the following should work:

```shell
# only do this if you do not already have a remote called `upstream`
git remote add upstream https://github.com/gavanderhoorn/comet_rpc.git
git fetch upstream

# create a new local branch into which we'll import your two commits
git checkout -b new_rpcs upstream/master
git cherry-pick 4dfb25d3
git cherry-pick e5b9d4d2

# if the previous two cherry-picks didn't result in any conflicts, push your new branch to GitHub
git push origin new_rpcs
```

at this point you should be able to create a new PR -- unfortunately you can't update this one easily, as you're using your `master` branch.

If you do get conflicts when cherry-picking, let me know.

**Comment by anandmit93** [comment]
So, when I try perform git cherry-pick, I get this error 
image

**Comment by gavanderhoorn** [comment]
I assumed you had no uncommitted changes.

I don't know what changes you do have, so you'd have to figure out whether you'd want to save them somewhere.

A `git status` might show what changes git believes you still have uncommitted.

(PS: could you please copy-paste terminal text just as text here in your comment? You can use [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) to make sure it's formatted properly)

**Comment by anandmit93** [comment]
Hello @gavanderhoorn,

Sorry for the delay. I was able to execute the rebasing. Please have a look and let me know if everything is fine.

**Comment by gavanderhoorn** [comment]
Nice. You mean `cherry-pick` to the new branch, right?

Seems you just need to submit a new PR now.

You can probably start here: https://github.com/gavanderhoorn/comet_rpc/compare/master...anandmit93:comet_rpc:new_rpcs.

**Comment by gavanderhoorn** [comment]
Thanks @anandmit93.

Commit history is much cleaner now 👍 

Replacement in #9.

**Pull request closed without merging**
