### PR TITLE
New RPCs: REMARKLIN, IODRYRUN and IOWETRUN

### PR DESCRIPTION
**Pull request by anandmit93**

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Hi @anandmit93, just letting you know I've not forgotten your PR.

**Comment by gavanderhoorn** [comment]
I'd also like to start adding revision information to the readme for RPCs which were introduced in a specific revision of system software.

Context: https://github.com/gavanderhoorn/comet_rpc/pull/6/files#r1229440297.

@anandmit93: if you could comment there as to which specific version you 

I've assumed it was only the `V9.40/43` system which supported `REMARKLIN`, so c43476c already updates the readme with that info.

**Comment by anandmit93** [comment]
Hello @gavanderhoorn,

Thank you for the update. I am unable to post the htm response file here but the response is like `{"FANUC":{"name":"TESTPC","fastclock":"35480","RPC":[{"rpc":"215","status":"0x0","lin_num":"3"}]}}` for REMARKLIN HTTP request.

**Comment by gavanderhoorn** [comment]
Is `lin_num` the number of lines that were (un)commented?

**Comment by anandmit93** [comment]
No, as per the HTTP request, the comments will be applied for line 1 and 2 only. I tried few more times with different `end` values and the `lin_num` is always 'end' + 1. First I assumed that the program pointer would be shifted to the lin_num value but it seems to be that the program pointer is always in line 1. I could not find why it is so.

One more point I observed is that when the `end` value is greater than the number of lines in pgoram, Error `0x7001B` is thrown in `status` which has  `Specified line does not exist` description. In this case, the `lin_num` value is always `last line of program + 1` (If program has 5 lines, then lin_num = 6).

**Comment by gavanderhoorn** [comment]
Hm, ok. Thanks for that.

In any case, we'd need to add the `lin_num` field to the `RemarkLinResponse`. It doesn't appear to have it right now.

**Comment by anandmit93** [comment]
I have just included `lin_num` field to `RemarkLinResponse` in messages.py. Please have a look.

**Review by gavanderhoorn — APPROVED** [review]
Looks like we can merge this.

I can't test `REMARKLIN` myself (yet), but based on the discussion in this PR I believe the current implementation should work.

Thanks again for the PR @anandmit93 👍

**Pull request merged**
